//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ZoomPlus.rc
//
#define IDC_MYICON                      2
#define IDC_MYICON2                     3
#define IDM_ABOUTBOX                    0x0010
#define IDM_OPTIONS                     0x0020
#define IDD_ZOOMPLUS_DIALOG             102
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDC_POINTER                     104
#define IDM_EXIT                        105
#define IDC_ARROW_ZOOMPLUS              106
#define IDI_ZOOMPLUS                    107
#define IDI_SMALL                       108
#define IDC_ZOOMPLUS                    109
#define ID_REBAR                        110
#define ID_ALWAYSONTOP                  112
#define ID_ZOOM                         113
#define ID_UPDATE                       114
#define ID_TOOLBAR                      115
#define ID_MAINSCREEN                   116
#define IDR_MAINFRAME                   128
#define ID_ACCEL                        134
#define IDR_MAIN_TOOLBAR                135
#define IDD_SAVE_BITMAP_TEMPLATE        138
#define IDR_CONTEXT_MENU                141
#define IDD_OPTIONS                     142
#define IDD_NAG_SCREEN                  143
#define IDB_HORIZONTAL_BITMAP           144
#define IDB_VERTICAL_BITMAP             145
#define IDC_ZOOMCURSOR                  145
#define IDC_MAIL_ME_STATIC              1000
#define IDC_VISIT_ME_STATIC             1001
#define IDC_SCREEN_IMAGE                1002
#define IDC_RGB                         1003
#define IDC_HEXADECIMAL                 1004
#define IDC_UPDATE_SLOW                 1005
#define IDC_UPDATE_SLOW_SPIN            1006
#define IDC_UPDATE_MEDIUM               1007
#define IDC_UPDATE_MEDIUM_SPIN          1008
#define IDC_UPDATE_FAST                 1009
#define IDC_UPDATE_FAST_SPIN            1010
#define IDC_DISPLAY_MOUSE               1011
#define IDC_INSTANCE                    1013
#define IDC_REGNUMBER                   1014
#define IDC_REGISTER                    1015
#define IDC_EVALUATE                    1016
#define IDC_VERSION_STATIC              1017
#define IDC_GRID_SIZE                   1018
#define IDC_GRID_SIZE_SPIN              1019
#define IDC_COLOUR                      1020
#define IDC_RELATIVE                    1021
#define IDC_TRANSPARENT                 1022
#define IDC_OSCURSOR                    1023
#define IDC_HOTKEY_BITMAP               1024
#define IDC_HOTKEY_COLOUR               1025
#define IDS_REBAR_TEXT                  4000
#define IDS_SAVE_AS_FILE_MASK           4001
#define IDS_AUTO_UPDATE_FORMAT          4002
#define IDS_APP_TITLE                   4003
#define IDS_FAILED_TO_WRITE_DIB         4004
#define IDS_FAILED_TO_ACQUIRE_DIB       4005
#define IDS_ZOOM_LEVEL_FORMAT           4006
#define ID_FOLLOW_MOUSE                 4009
#define ID_2X                           4011
#define ID_4X                           4012
#define ID_WHATS_THIS                   4013
#define ID_HELP                         4014
#define ID_TOGGLE_TOOLBAR               4015
#define ID_TOGGLE_STATUSBAR             4016
#define ID_OPTIONS                      4017
#define ID_COPYSCREENSELECTION          4018
#define ID_SAVESELECTION                4020
#define ID_COPYSCREENSELECTION_ZOOMED   4021
#define ID_CONTEXT_MENU                 4022
#define ID_CANCEL                       4023
#define ID_ZOOM_TO                      4024
#define ID_0_HIGHLIGHT                  4025
#define ID_HIGHLIGHT                    4026
#define ID_GRID                         4027
#define ID_OPTION_RGB                   4028
#define ID_OPTION_HEX                   4029
#define ID_OPTION_SCREEN_COORDINATES    4030
#define ID_OPTION_WINDOW_COORDINATES    4031
#define ID_TOGGLE_TRANSPARENT           4032
#define ID_COPY_TO_CLIPBOARD            32771
#define ID_COPY_TO_CLIPBOARD_SCREEN     32772
#define ID_SAVE_AS                      32774
#define ID_ZOOMIN                       32775
#define ID_ZOOMOUT                      32776
#define ID_ABOUT                        32779
#define ID_UPDATE_PLUS                  32780
#define ID_UPDATE_MINUS                 32781
#define ID_SIZE_BITMAP                  32782
#define IDS_MAIL_ME_URL                 32783
#define IDS_VISIT_ME_URL                32784
#define IDS_DEFAULT_STATUSBAR_TEXT      32785
#define IDS_WIDEST_RGB                  32786
#define IDS_RGB_FORMAT                  32787
#define IDS_WIDEST_COORDS               32788
#define IDS_COORDS_FORMAT               32789
#define IDS_OPTIONS_UPDATE_FAILED       32790
#define IDS_HEX_FORMAT                  32791
#define IDS_SELECT_RECTANGLE_DIMENSIONS 32792
#define IDS_ABOUT_ZOOM_PLUS             32793
#define IDS_SOMETHING_WENT_WRONG        32794
#define IDS_BAD_REG_NUMBER              32795
#define IDS_REGISTERED                  32796
#define IDS_OPTIONS_GRIDSIZE_FAILED     32797
#define IDS_OPTIONS                     32798
#define IDS_GIPSYSOFT                   32799
#define IDS_STATUSBAR_TIP_URL           32800
#define IDS_STATUSBAR_TIP_COLOR_RGB     32801
#define IDS_STATUSBAR_TIP_COORDINATES   32802
#define IDS_STATUSBAR_TIP_COLOR         32803
#define IDS_DRAG_ZOOM_INSTRUCTIONS      32804
#define IDS_DRAG_SELECTION_TIP          32805
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         4035
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
